-- CREA LA BBDD SI NO EXISTE --
CREATE DATABASE IF NOT EXISTS `SOSANIMALES`;

-- USAR LA BBDD SI EXISTE --
USE `SOSANIMALES`;

CREATE TABLE IF NOT EXISTS `SOSANIMALES`.`T_COLOR` (
    `ID` INT NOT NULL AUTO_INCREMENT,
    `COLOR` VARCHAR(45) NOT NULL,
    PRIMARY KEY (`ID`)
);

CREATE TABLE IF NOT EXISTS `SOSANIMALES`.`T_TAMAÑO` (
    `ID` INT NOT NULL AUTO_INCREMENT,
    `TAMAÑO` VARCHAR(45) NOT NULL,
    PRIMARY KEY (`ID`)
);

CREATE TABLE IF NOT EXISTS `SOSANIMALES`.`T_ESTADO` (
    `ID` INT NOT NULL AUTO_INCREMENT,
    `ESTADO` VARCHAR(45) NOT NULL,
    PRIMARY KEY (`ID`)
);

CREATE TABLE IF NOT EXISTS `SOSANIMALES`.`T_ESPECIE` (
    `ID` INT NOT NULL AUTO_INCREMENT,
    `ESPECIE` VARCHAR(45) NOT NULL,
    PRIMARY KEY (`ID`)
);

CREATE TABLE IF NOT EXISTS `SOSANIMALES`.`T_ANIMAL` (
    `ID` INT NOT NULL AUTO_INCREMENT,
    `NOMBRE` VARCHAR(45) NOT NULL,
    `DESCRIPCION` VARCHAR(100) NOT NULL,
    `IMAGEN` VARCHAR(100) NOT NULL,
    `COLOR_ID` INT,
    `TAMAÑO_ID` INT,
    `ESPECIE_ID` INT,
    PRIMARY KEY (`ID`)
);

CREATE TABLE IF NOT EXISTS `SOSANIMALES`.`T_USUARIO` (
    `ID` INT NOT NULL AUTO_INCREMENT,
    `NOMBRE` VARCHAR(45) NOT NULL,
    `EMAIL` VARCHAR(50) NOT NULL,
    `CONTRASEÑA` VARCHAR(25) NOT NULL,
    `TELEFONO` VARCHAR(20) NOT NULL,
    PRIMARY KEY (`ID`)
);

CREATE TABLE IF NOT EXISTS `SOSANIMALES`.`T_TOKEN` (
    `ID` INT NOT NULL AUTO_INCREMENT,
    `TOKEN` VARCHAR(50) NOT NULL,
    `FECHAVENCIMIENTO` DATETIME NOT NULL,
    `FECHACREACION` DATETIME NOT NULL,
    `ULTIMACONEXION` DATETIME NOT NULL,
    `USUARIO_ID` INT,
    PRIMARY KEY (`ID`)
);

CREATE TABLE IF NOT EXISTS `SOSANIMALES`.`T_CONTACTOEXTRA` (
    `ID` INT NOT NULL AUTO_INCREMENT,
    `NOMBRE` VARCHAR(45) NOT NULL,
    `TELEFONO` VARCHAR(20) NOT NULL,
    `EMAIL` VARCHAR(50) NULL,
    PRIMARY KEY (`ID`)
);

CREATE TABLE IF NOT EXISTS `SOSANIMALES`.`T_AVISO` (
    `ID` INT NOT NULL AUTO_INCREMENT,
    `FECHADESAPARECIDO` DATETIME NOT NULL,
    `LUGARDESAPARECIDO` VARCHAR(100) NOT NULL,
    `ANIMAL_ID` INT,
    `CONTACTOEXTRA_ID` INT,
    `ESTADO_ID` INT,
    PRIMARY KEY (`ID`)
);

-- AÑADIMOS LAS CLAVES FORÁNEAS --
ALTER TABLE `SOSANIMALES`.`T_ANIMAL`
    ADD FOREIGN KEY (`COLOR_ID`) REFERENCES `T_COLOR`(`ID`) ON DELETE CASCADE ON UPDATE CASCADE,
    ADD FOREIGN KEY (`TAMAÑO_ID`) REFERENCES `T_TAMAÑO`(`ID`) ON DELETE CASCADE  ON UPDATE CASCADE,
    ADD FOREIGN KEY (`ESPECIE_ID`) REFERENCES `T_ESPECIE`(`ID`) ON DELETE CASCADE  ON UPDATE CASCADE;

ALTER TABLE `SOSANIMALES`.`T_TOKEN`
    ADD FOREIGN KEY (`USUARIO_ID`) REFERENCES `T_USUARIO`(`ID`) ON DELETE CASCADE  ON UPDATE CASCADE;

ALTER TABLE `SOSANIMALES`.`T_AVISO`
    ADD FOREIGN KEY (`ANIMAL_ID`) REFERENCES `T_ANIMAL`(`ID`) ON DELETE CASCADE  ON UPDATE CASCADE,
    ADD FOREIGN KEY (`CONTACTOEXTRA_ID`) REFERENCES `T_CONTACTOEXTRA`(`ID`) ON DELETE CASCADE  ON UPDATE CASCADE,
    ADD FOREIGN KEY (`ESTADO_ID`) REFERENCES `T_ESTADO`(`ID`) ON DELETE CASCADE  ON UPDATE CASCADE;

-- AÑADIMOS EL CONTENIDO DE LAS TABLAS --
INSERT INTO `SOSANIMALES`.`T_COLOR` (`COLOR`) VALUES ('BLANCO');
INSERT INTO `SOSANIMALES`.`T_COLOR` (`COLOR`) VALUES ('NEGRO');
INSERT INTO `SOSANIMALES`.`T_COLOR` (`COLOR`) VALUES ('GRIS');
INSERT INTO `SOSANIMALES`.`T_COLOR` (`COLOR`) VALUES ('MARRON');

INSERT INTO `SOSANIMALES`.`T_TAMAÑO` (`TAMAÑO`) VALUES ('PEQUEÑO');
INSERT INTO `SOSANIMALES`.`T_TAMAÑO` (`TAMAÑO`) VALUES ('MEDIANO');
INSERT INTO `SOSANIMALES`.`T_TAMAÑO` (`TAMAÑO`) VALUES ('GRANDE');

INSERT INTO `SOSANIMALES`.`T_ESPECIE` (`ESPECIE`) VALUES ('PERRO');
INSERT INTO `SOSANIMALES`.`T_ESPECIE` (`ESPECIE`) VALUES ('GATO');

INSERT INTO `SOSANIMALES`.`T_ESTADO` (`ESTADO`) VALUES ('PERDIDO');
INSERT INTO `SOSANIMALES`.`T_ESTADO` (`ESTADO`) VALUES ('ENCONTRADO');
INSERT INTO `SOSANIMALES`.`T_ESTADO` (`ESTADO`) VALUES ('DEVUELTO');
